// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKhGevNrI8lalLXoOMWl8Zx_FI6sq7nBI',
    appId: '1:647169473197:web:0ba3e23049827d7f1d2424',
    messagingSenderId: '647169473197',
    projectId: 'pinote-chat-app',
    authDomain: 'pinote-chat-app.firebaseapp.com',
    storageBucket: 'pinote-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYUinOZvojrsKctHujJyQ7b-plDmePLbw',
    appId: '1:647169473197:android:359df9b3416495511d2424',
    messagingSenderId: '647169473197',
    projectId: 'pinote-chat-app',
    storageBucket: 'pinote-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAENvaD32nq29o446vRXks9x_wpaqY5X6w',
    appId: '1:647169473197:ios:6f64af35c6a3b5bf1d2424',
    messagingSenderId: '647169473197',
    projectId: 'pinote-chat-app',
    storageBucket: 'pinote-chat-app.appspot.com',
    iosClientId: '647169473197-lvbd5uvevorfqfutfb2fj0ga3rghrbnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
